### ISSUE TITLE
Async/Await Backward Compatibility

### ISSUE THREAD

**Issue by dnKaratzas** [vapor/websocket-kit#112]
Starting in Xcode 13.2, Swift’s new suite of concurrency features are now backward compatible all the way back to iOS 13, macOS 10.15, watchOS 6, and tvOS 13

**Comment by 0xTim** [comment]
So unfortunately this isn't that simple because we can't guarantee what versions of Xcode people are using. Both Xcode 13.0 and 13.1 will no longer compile with the PR as is because they don't have a concurrency runtime. We'd need to duplicate all the APIs and have copies for 5.5 but old Xcode and 5.5 but new Xcode. As such, we are choosing not to support older Apple platforms and stick with what we have. Does that make sense?
